# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Organization"
  url = "#organization"
  weight = 20

[[main]]
  name = "Material"
  url = "/post/"
  weight = 30


[[main]]
  name = "Help"
  url = "#help"
  weight = 40
  
[[main]]
  name = "People"
  url = "#people"
  weight = 50

[[main]]
  name = "Syllabus"
  url = "/syllabus"
  weight = 60
  
[[main]]
  name = "Roadmap"
  url = "/roadmap"
  weight = 70

[[main]]
  name = "Misc"
  url = "/misc"
  weight = 80  
  
[[main]]
  name = "<i class='fab fa-github'></i>"
  url = "https://github.com/uni-mannheim-qm-2021"
  weight = 100
  
[[main]]
  name = "<i class='fab fa-slack'></i>"
  url = "https://qm2021.slack.com"
  weight = 120

[[main]]
  name = "<i class='fas fa-university'></i>"
  url = "https://ilias.uni-mannheim.de/"
  weight = 130
